- hosts: localhost
  connection: local
  tasks:
  - name: Retrieve secrets from AWS Secrets Manager
    set_fact:
      api_key: "{{ lookup('aws_secret', 'kannan/poc') }}"
  - name: Print secrets
    debug:
      var: api_key